// Package manifest describes the repository-wide input kix receives from Nix,
// generated by the flake-parts module and used by seal and edit.
package manifest

import (
	"encoding/json"
	"fmt"
	"os"
)

type Manifest struct {
	// Identity decrypts the source .age files.
	Identity string `json:"identity"`
	// Cache is where sealed secrets are written, relative to the flake root.
	Cache string `json:"cache"`
	// SecretsDir holds the source .age files, relative to the flake root.
	SecretsDir string `json:"secretsDir"`
	// ExtraRecipients are encrypted to on top of Identity's own recipient.
	ExtraRecipients []string `json:"extraRecipients"`
	// Profiles are store paths of the per-host profile JSON files.
	Profiles []string `json:"profiles"`
}

func Load(path string) (*Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading manifest %q: %w", path, err)
	}
	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parsing manifest %q: %w", path, err)
	}
	return &m, nil
}
