// Package manifest describes the top-level input kix receives from Nix for
// repository-wide operations (seal, edit).
//
// The manifest is generated by the flake-parts module. It is the single place
// that knows about every node, so argv does not grow with the number of hosts.
package manifest

import (
	"encoding/json"
	"fmt"
	"os"
)

type Manifest struct {
	// Identity is the master identity used to decrypt source .age files.
	Identity string `json:"identity"`

	// Cache is the directory sealed per-host secrets are written to,
	// relative to the flake root.
	Cache string `json:"cache"`

	// ExtraRecipients are additional recipients source .age files are
	// encrypted to, on top of the master identity's own recipient.
	ExtraRecipients []string `json:"extraRecipients"`

	// Profiles are store paths of the per-host profile JSON files.
	Profiles []string `json:"profiles"`
}

func Load(path string) (*Manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading manifest %q: %w", path, err)
	}
	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("parsing manifest %q: %w", path, err)
	}
	return &m, nil
}
